export const GET_USERS = "GET_USERS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILURE = "GET_USERS_FAILURE";

export const GET_USER_DETAIL = "GET_USER_DETAIL";
export const GET_USER_DETAIL_SUCCESS = "GET_USER_DETAIL_SUCCESS";
export const GET_USER_DETAIL_FAILURE = "GET_USER_DETAIL_FAILURE";

export const GET_USER_REPO = "GET_USER_REPO";
export const GET_USER_REPO_SUCCESS = "GET_USER_REPO_SUCCESS";
export const GET_USER_REPO_FAILURE = "GET_USER_REPO_FAILURE";
